aio-libs/aiodns

README.rst
aiodns/__init__.py
tests.py

This PR adds a `gethostbyname()` method to `DNSResolver`.
`ares_query()` always performs a DNS query, while `ares_gethostbyname()` first checks `/etc/hosts`.
It matters when trying to resolve hostnames like `localhost` (as described in #17).
The `cb()` function defined in `query()` is now a static method of the class, as it is reused in `gethostbyname()`. I implemented three tests: one with `AF_INET`, `AF_INET6` and one with an incorrect integer value ensuring the error generated by ares is set in the future.
as a side, I ensured the loop is explicitly closed after each test to avoid `ResourceWarning`s being displayed.

add DNSResolver.gethostbyname()

---

aiodns/__init__.py
setup.py

- Add in Py2/3 compatible PEP484 typing
- Add in typing as a install_requires in setup.py

Add PEP484 Typing + typing to setup.py

---

tests.py

`sys.version[:3]` won't return the right thing in Python 3.10.
Use the [`sys.version_info`](https://docs.python.org/3/library/sys.html#sys.version_info) tuple instead.

Fix Python version check

---

README.rst
aiodns/__init__.py
tests.py

Hi,
Thanks for this package! I have the need to make async reverse lookups.
I was able to add the `gethostbyaddr` from the pycares package here pretty quickly. Is this something that is interesting for you to support? If so please tell me if you need me to make changes to the testing or flesh out the documentation a bit more.
Please note that I don't know that much about the underlying mechanisms here.

implement gethostbyaddr for reverse lookups

---

aiodns/__init__.py
setup.py

There is no Channel.destroy() method anymore.

Raise pycares dependency

---

README.rst

The current README does not display properly on PyPi. This is because the duplicate target name in the README `the documentation`. Current PR README can be viewed at https://test.pypi.org/project/aiodns/. Closes #67

Updated README for proper display on PyPi

---

aiodns/__init__.py

The underlying pycares expects int (enum) for gethostbyname() but our type annotation says 'str'.

Fix type annotation of gethostbyname()

---

.gitignore
.travis.yml
aiodns/__init__.py
mypy.ini
mypy_run.py

- Lets ensure we stay type awesome.

Add mypy to CI for cpython

---

.github/workflows/ci.yml
tests.py

Remove loop= param from asyncio.sleep() to fix tests on Python 3.10

---

aiodns/__init__.py

This fixes the return type for the nameservers method based on the actual pycares return type

Fix return type for resolver nameservers

---

MANIFEST.in

Added the py.typed file so that when someone uses this library they can parse their typed with mypy
This was pointed out in #93

Add PEP-561 with py.typed

---

tests.py

This makes the equivalent change for aiodns to one of the pycares changes I sent yesterday.

Update test_query_ptr test to use address with PTR record

---

setup.py

Hi. Types and a py.typed marker have been added in PR #109.
The marker was also specified in [MANIFEST.in](https://github.com/saghul/aiodns/blob/master/MANIFEST.in#L3)
Unfortunately MANIFEST.in [does not affect](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#manifest-in) binary distributions such as wheels. 
This is the structure of the RECORD file during the installation of the package from wheel
```
aiodns-3.1.1.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
aiodns-3.1.1.dist-info/LICENSE,sha256=6wRV01EpQl7TmYg81xCSPePiRqUQ4uuE2fAAMtC77Jc,1070
aiodns-3.1.1.dist-info/METADATA,sha256=qM6KoP0Ot6pFAF-izMoNBgmGsIlTQfieU4X0nN5lobI,3994
aiodns-3.1.1.dist-info/RECORD,,
aiodns-3.1.1.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCe …
```

Added a missing py.typed file for wheel

---

aiodns/__init__.py
tests.py

So I recently tried to see if `winloop`  would be another valid option since it is not tied to the `ProctorEventLoop` in any way shape or form and I was able to spin up a quick unittest once I modified aiodns's dns resolver to work with my library.
```python
try:
import aiodns
except ImportError:
skip_tests = True
else:
skip_tests = False
import asyncio
import sys
import unittest
import weakref
from winloop import _testbase as tb
class _TestAiodns:
def test_dns_query(self):
resolver = aiodns.DNSResolver(loop=self.loop)
async def test():
async def query(name, query_type):
return await resolver.query(name, query_type)
await query('google.com', 'A')
await query('httpbin.org', 'A')
await query('example.com', 'A')
self.loop.run_until_complete(test())
@unittest.skipIf(skip_tests, "no aiodns …
```

Add Winloop as a valid EventLoop

---

aiodns/__init__.py
tests.py

The end goal is to be able to use this in aiohttp's resolver https://github.com/aio-libs/aiohttp/blob/aa014a9c1084368a01a79f09bb238486e0aa164a/aiohttp/resolver.py#L91 as the current implementation doesn't return both IPv6 and IPv4 addresses which provides different semantics than the threaded resolver which uses python's built-in `getaddrinfo`
fixes #23 https://github.com/saghul/aiodns/issues/23#issuecomment-1055456917
We are going to be rolling out Happy Eyeballs support in `aiohttp` 3.10.x so it would be nice to be able to avoid the threads

Add support for getaddrinfo

---

aiodns/__init__.py
tests.py

This is a followup to #118 to add `getnameinfo` as well to support https://github.com/aio-libs/aiohttp/pull/8270

Add support for getnameinfo

---

.github/workflows/release-wheels.yml

I also switched it over to trusted publishing since its already set up.

Fix release workflow for breaking changes in upload/download artifact

---

ChangeLog
aiodns/__init__.py

3.4.0
=====
- Added fallback to `sock_state_cb` if `event_thread` creation fails (#151)
- Improved reliability on systems with exhausted inotify watches
- Implemented transparent fallback mechanism to ensure DNS resolution continues to work
- Implemented strict typing (#138)
- Added comprehensive type annotations
- Improved mypy configuration
- Added py.typed marker file
- Updated dependencies
- Bumped pycares from 4.7.0 to 4.8.0 (#149)
- Added support for Python 3.13 (#153)
- Updated CI configuration to test with Python 3.13

Release 3.4.0

---

aiodns/__init__.py

Fixes the return type signature of DNSResolver query to not lie to users about what is returned. Properly reflects what Pycares actually returns for each query type.
Return type signature now matches reality of what is returned
Fixes #161 
- [] Unit tests for the changes exist
- [] Documentation reflects the changes
Change does not change library functionality.

Fix return type signature for CNAME and SOA records

---

README.rst
aiodns/__init__.py
requirements.txt
setup.py
tests/test_aiodns.py

This PR adds a `close()` method to the `DNSResolver` class to allow for explicit cleanup of resources. The implementation includes:
- New `close()` method that cleanly shuts down the resolver by canceling timers, removing file descriptors, and closing the pycares channel
- Async context manager support (`__aenter__` and `__aexit__`) for automatic cleanup when using `async with`
- Improved `__del__` method that automatically calls cleanup when the resolver is garbage collected
- Comprehensive test coverage for all new functionality
- **New feature**: Users can now explicitly close resolvers with `await resolver.close()`
- **New feature**: Resolvers can be used as async context managers: `async with aiodns.DNSResolver() as resolver:`
- **Improved cleanup**: Resolvers will automatically …

Add explict close method

---

ChangeLog
aiodns/__init__.py

- Added explicit close method (#166)
- Allows proper cleanup of resources on demand
- Fixed return type signature for CNAME and SOA records (#162)
- Corrected type annotations for better type checking
- Improved Windows event loop documentation (#163)
- Provided more accurate information on supported event loops on Windows
- Added pre-commit configuration with ruff (#152)
- Improved code quality and consistency
- Reformatted code and normalized end-of-line characters (#155)
- Updated dependencies
- Bumped pycares from 4.8.0 to 4.9.0 (#168)
- Bumped pytest-asyncio from 0.26.0 to 1.0.0 (#167)
- Bumped pytest-cov from 6.1.1 to 6.2.1 (#164)
- Bumped pytest from 8.3.5 to 8.4.0 (#160)
- Bumped mypy from 1.15.0 to 1.16.0 (#158)
- Bumped dependabot/fetch-metadata from 2.3.0 to 2.4.0 (#159)

Release 3.5.0

---

aiodns/__init__.py

These changes are meant to speedup socket callbacks for the read and write file descriptors making the dns resolver run a bit smoother. 
Removed some internal flags related to read and write but I don't think anybody is ever going to use them to begin with.

Socket Callback Optimizations 
